# Generated by Django 5.1.4 on 2025-02-17 10:48

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Nom utilisateur')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name="Statut d'équipe(Super Utilisateur)")),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrateur')),
                ('is_agent', models.BooleanField(default=False, verbose_name='Agent')),
                ('is_student', models.BooleanField(default=False, verbose_name='Etudiant')),
                ('is_allowed', models.BooleanField(default=False, verbose_name='Autorisé')),
                ('level', models.IntegerField(default=0, verbose_name='Niveau')),
                ('domain', models.CharField(choices=[('informatique', 'Informatique (Basic)'), ('telecommunication', 'Télécommunication'), ('reseau_informatique', 'Réseau informatique'), ('administration_reseau', 'Administration réseau'), ('technologie_vsat', 'Technologie VSAT'), ('programmation_informatique', 'Programmation informatique')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField()),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog_imgs/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Article_blog',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Titre')),
                ('book_file', models.FileField(null=True, upload_to='file_pdf/', verbose_name='Fichier PDF')),
                ('domain', models.CharField(choices=[('informatique', 'Informatique (Basic)'), ('telecommunication', 'Télécommunication'), ('reseau_informatique', 'Réseau informatique'), ('administration_reseau', 'Administration réseau'), ('technologie_vsat', 'Technologie VSAT'), ('programmation_informatique', 'Programmation informatique')], max_length=30)),
                ('level', models.IntegerField(verbose_name='Niveau')),
                ('description', models.TextField(blank=True, unique=True, verbose_name='Déscription')),
                ('student', models.ManyToManyField(related_name='document', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Projet(Tache)')),
                ('description', models.TextField()),
                ('date_de_debut', models.DateField()),
                ('date_de_fin', models.DateField(blank=True, null=True)),
                ('priorite', models.CharField(choices=[('absolue', 'Absolue'), ('haute', 'Haute'), ('Moyenne', 'Moyenne'), ('basse', 'Basse')], max_length=20)),
                ('statut', models.CharField(choices=[('non debute', 'Non debuté'), ('en cours', 'En cours'), ('termine', 'Terminé')], max_length=20)),
                ('avancement', models.IntegerField(default=0)),
                ('commentaires', models.TextField()),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tache',
                'ordering': ['-date_de_debut'],
            },
        ),
    ]
