# Generated by Django 5.1.4 on 2025-02-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='student',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='domain',
            field=models.CharField(choices=[('informatique', 'Informatique (Basic)'), ('telecommunication', 'Télécommunication'), ('reseau_informatique', 'Réseau informatique'), ('administration_reseau', 'Administration réseau'), ('technologie_vsat', 'Technologie VSAT'), ('programmation_informatique', 'Programmation informatique')], max_length=30, verbose_name='Orientation'),
        ),
    ]
