# Generated by Django 5.1.4 on 2025-02-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_document_student_alter_customuser_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='our_entervention',
            field=models.BooleanField(default=False, verbose_name='Categorie Intervention'),
        ),
    ]
