# Generated by Django 5.1.4 on 2025-02-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_our_entervention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='our_entervention',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='our_intervention',
            field=models.BooleanField(default=False, verbose_name="Categorie intervention de l'entreprise"),
        ),
    ]
